<b>What is a Matrix?

A matrix is simply a rectangular arrangement of numbers (or variables) in rows and columns.



# <span style="color:#2563EB;">Matrix Operations (Short Notes)</span>

---

### ➤ Matrix Addition (+)
- Same order required (same rows & columns)
- Add corresponding elements

$$
A+B=
\begin{bmatrix}
a_{11}+b_{11} & a_{12}+b_{12}\\
a_{21}+b_{21} & a_{22}+b_{22}
\end{bmatrix}
$$

---

### ➤ Matrix Subtraction (−)
- Same order required
- Subtract corresponding elements

$$
A-B=
\begin{bmatrix}
a_{11}-b_{11} & a_{12}-b_{12}\\
a_{21}-b_{21} & a_{22}-b_{22}
\end{bmatrix}
$$

---

### ➤ Scalar Multiplication (kA)
- Multiply every element by scalar **k**

$$
kA=[ka_{ij}]
$$

---

### ➤ Matrix Multiplication (AB)
- Possible only if:

$$
\text{Columns of }A=\text{Rows of }B
$$

- If

$$
A_{m\times n},\quad B_{n\times p}
$$

then

$$
AB=A_{m\times p}
$$

- **Rule:** Row × Column

---

### ➤ Transpose $(A^T)$
- Rows become columns

$$
(A^T)_{ij}=A_{ji}
$$

---

### ➤ Determinant
- Defined only for **Square Matrix**

**Notation**

$$
|A| \quad \text{or} \quad \det(A)
$$

---

### ➤ Inverse
- Exists only for some square matrices

**Notation**

$$
A^{-1}
$$

**Property**

$$
AA^{-1}=I
$$

where **I = Identity Matrix**

---

## <span style="color:#16A34A;">Conditions</span>

| Operation | Condition |
|:----------|:----------|
| Addition | Same order |
| Subtraction | Same order |
| Multiplication | Columns(A) = Rows(B) |
| Determinant | Square Matrix |
| Inverse | Square Matrix & $\det(A)\neq0$ |

| Dimensions | Name   | Example                          |
| ---------- | ------ | -------------------------------- |
| **0D**     | Scalar | `5`                              |
| **1D**     | Vector | `[1, 2, 3]`                      |
| **2D**     | Matrix | `[[1,2],[3,4]]`                  |
| **3D**     | Tensor | `[[[...],[...]], [[...],[...]]]` |
| **nD**     | Tensor | 4D, 5D, ...                      |


<b> Matrix Addition 

In [4]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.add(A, B)

print(C)



#Matrix Addition requires matrices to have the same order (same rows and columns).


#matrix substraction is also same


[[ 6  8]
 [10 12]]


<b> Matrix Multiplied by Scaler 

In [5]:
A = np.array([[1, 2],
              [3, 4]])

result = 2 * A

print(result)

[[2 4]
 [6 8]]


<b> Matrix Multiplication  

In [14]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A @ B 

print(C)

[[19 22]
 [43 50]]


In [15]:
A.shape
B.shape

(2, 2)

##### Matrix multiplication is not like normal multiplication. You multiply rows of the first matrix with columns of the second matrix.

<b> Matrix Transpose

In [16]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]
