| Data type                | Typical architecture               | Why?                                        |
| ------------------------ | ---------------------------------- | ------------------------------------------- |
| 📊 **Tabular data**      | **ANN / MLP**                      | Each row is mostly independent              |
| 🖼️ **Image data**       | **CNN**                            | Nearby pixels have spatial relationships    |
| 📝 **Sequential data**   | **RNN**                            | The **order of data matters**               |
| ⏳ **Time-series data**   | **RNN / LSTM / GRU**               | Previous values can influence future values |
| 🗣️ **Text / sentences** | **RNN / LSTM / GRU / Transformer** | Word order and context matter               |
| 🎵 **Audio / speech**    | **RNN / CNN / Transformer**        | Data arrives as a sequence                  |


<h2 style="
color: #1B4F72;
border-bottom: 4px solid #3498DB;
padding-bottom: 8px;
font-weight: 800;
">
What is Sequential Data?
</h2>

> **Sequential data is data where the order of elements matters.**

### <span style="color:#2980B9;">Examples</span>

- **Text:** `I → love → ML`
- **Stock Prices:** `100 → 105 → 110 → ...`
- **Temperature:** `25°C → 27°C → 30°C`
- **Audio / Music:** `Sound₁ → Sound₂ → Sound₃`
- **Sensor Data:** `t₁ → t₂ → t₃ → ...`

### <span style="color:#8E44AD;">Key Idea</span>

> **Past information can help understand or predict future information.**

### <span style="color:#16A085;">Common Architectures</span>

```text
Sequential Data
      ↓
RNN / LSTM / GRU
      ↓
Transformer
```

<h2 style="
color: #1B4F72;
border-bottom: 4px solid #3498DB;
padding-bottom: 8px;
font-weight: 800;
">
🔄 RNN (Recurrent Neural Network)
</h2>

> **RNN = Recurrent Neural Network**
>
> A type of neural network designed to work with **sequential data**, where the order of data matters.

---

<h2 style="
color: #7D3C98;
border-bottom: 4px solid #AF7AC5;
padding-bottom: 8px;
font-weight: 800;
">
📌 What is Sequential Data?
</h2>

Sequential data is data where **the order of elements carries meaning**.

### Examples

- 📝 Text → words come in an order
- 🎤 Speech → sounds occur over time
- 📈 Time-series → stock price, temperature, sales
- 🎬 Video → frames occur sequentially
- ⌨️ Typing → previous characters/words matter

Example:

```text
I → love → machine → learning
```

Changing the order changes the meaning:

```text
learning → machine → love → I
```

---

<h2 style="
color: #0E6251;
border-bottom: 4px solid #48C9B0;
padding-bottom: 8px;
font-weight: 800;
">
🤔 Why Do We Need RNN?
</h2>

Traditional ANN treats inputs mostly as independent.

For example:

```text
Input 1 ──┐
Input 2 ──┼──> ANN ──> Output
Input 3 ──┘
```

It doesn't naturally maintain information about **what came before**.

RNN introduces a **memory**.

```text
Previous information
        ↓
Input → RNN → Hidden State
        ↓
      Output
```

The hidden state carries information from previous time steps.

---

<h2 style="
color: #943126;
border-bottom: 4px solid #EC7063;
padding-bottom: 8px;
font-weight: 800;
">
🧠 Core Idea of RNN
</h2>

At every time step, RNN takes:

1. Current input `xₜ`
2. Previous hidden state `hₜ₋₁`

and produces:

1. New hidden state `hₜ`
2. Output `yₜ`

```text
          hₜ₋₁
             ↓
xₜ ──────> [ RNN ] ──────> hₜ
             │
             ↓
            yₜ
```

The important idea:

> **RNN remembers previous information through its hidden state.**

---

<h2 style="
color: #154360;
border-bottom: 4px solid #5DADE2;
padding-bottom: 8px;
font-weight: 800;
">
🔄 RNN Unrolled Through Time
</h2>

Suppose we have:

```text
I love machine learning
```

RNN processes one word at a time:

```text
x₁        x₂          x₃          x₄
I    →    love   →    machine →   learning
↓         ↓            ↓            ↓
RNN       RNN          RNN          RNN
↓         ↓            ↓            ↓
h₁   →    h₂     →     h₃     →     h₄
```

Each step receives information from the previous step.

```text
h₁ → h₂ → h₃ → h₄
```

So:

```text
h₄
```

contains information influenced by:

```text
I + love + machine + learning
```

---

<h2 style="
color: #6E2C00;
border-bottom: 4px solid #EB984E;
padding-bottom: 8px;
font-weight: 800;
">
🧮 RNN Mathematical Intuition
</h2>

The basic equation is:

hₜ = f(Wₓₕxₜ + Wₕₕhₜ₋₁ + b)

Where:

* `xₜ` → current input
* `hₜ₋₁` → previous hidden state
* `hₜ` → current hidden state
* `Wₓₕ` → input → hidden weights
* `Wₕₕ` → hidden → hidden weights
* `b` → bias
* `f` → activation function, commonly `tanh`

Output:

yₜ = Wₕᵧhₜ + bᵧ

---

<h2 style="
color: #186A3B;
border-bottom: 4px solid #58D68D;
padding-bottom: 8px;
font-weight: 800;
">
💡 Intuition Behind Hidden State
</h2>

Think of the hidden state as **short-term memory**.

Example:

```text
"The boy went to the bank because he needed..."
```

When RNN reaches:

```text
money
```

previous words can help determine the meaning.

The hidden state carries some information about previous words.

---

<h2 style="
color: #4A235A;
border-bottom: 4px solid #BB8FCE;
padding-bottom: 8px;
font-weight: 800;
">
🔁 RNN Weight Sharing
</h2>

One important property:

> **The same weights are reused at every time step.**

```text
       Same RNN parameters
       ↓      ↓      ↓

x₁ → [RNN] → [RNN] → [RNN] → [RNN]
       ↓       ↓       ↓       ↓
      h₁      h₂      h₃      h₄
```

This makes RNN much more parameter-efficient than creating a separate neural network for every time step.

---

<h2 style="
color: #7B241C;
border-bottom: 4px solid #F1948A;
padding-bottom: 8px;
font-weight: 800;
">
📊 RNN Input Shape
</h2>

For a typical batch of sequences:

```text
(batch_size, sequence_length, input_features)
```

Example:

```text
(32, 10, 50)
```

Means:

* `32` → number of sequences
* `10` → number of time steps
* `50` → features at each time step

For NLP:

```text
batch_size = 32
sequence_length = 10
embedding_size = 50
```

---

<h2 style="
color: #1A5276;
border-bottom: 4px solid #5499C7;
padding-bottom: 8px;
font-weight: 800;
">
🎯 Types of RNN Architectures
</h2>

## 1️⃣ One-to-One

```text
Input → Output
```

Example:

```text
Image → Class
```

Usually handled by normal neural networks, not specifically RNNs.

---

## 2️⃣ One-to-Many

```text
Input → Output sequence
```

Example:

```text
Image → Caption
```

---

## 3️⃣ Many-to-One

```text
Input sequence → Output
```

Example:

```text
"I love this movie"

        ↓

    Sentiment
        ↓
      Positive
```

Used for:

* Sentiment classification
* Spam detection
* Sequence classification

---

## 4️⃣ Many-to-Many

```text
Input sequence → Output sequence
```

Example:

```text
English sentence → Hindi sentence
```

Used in:

* Machine translation
* Sequence labeling
* Speech processing

---

<h2 style="
color: #873600;
border-bottom: 4px solid #DC7633;
padding-bottom: 8px;
font-weight: 800;
">
🚨 Main Problem with Basic RNN
</h2>

Basic RNN has difficulty remembering information from **very long sequences**.

Example:

```text
The cat ................. was hungry.
```

If the relevant information is very far away, the basic RNN may lose it.

This happens mainly because of:

### ❌ Vanishing Gradient

During Backpropagation Through Time (BPTT), gradients can become extremely small.

```text
Large sequence
     ↓
Gradient × Gradient × Gradient × ...
     ↓
Very small gradient
     ↓
Early information is poorly learned
```

Result:

> RNN struggles with **long-term dependencies**.

---

<h2 style="
color: #0B5345;
border-bottom: 4px solid #48C9B0;
padding-bottom: 8px;
font-weight: 800;
">
💥 Exploding Gradient
</h2>

The opposite problem can also occur.

Gradients become extremely large:

```text
Gradient × Gradient × Gradient
              ↓
       Very large value
              ↓
    Exploding Gradient
```

Common solutions include:

* Gradient clipping
* Better architectures such as LSTM/GRU

---

<h2 style="
color: #512E5F;
border-bottom: 4px solid #A569BD;
padding-bottom: 8px;
font-weight: 800;
">
🔥 RNN → LSTM → GRU
</h2>

Because vanilla RNN struggles with long-term dependencies, more advanced recurrent architectures were developed.

```text
Vanilla RNN
    ↓
   LSTM
    ↓
   GRU
```

### RNN

Simple memory mechanism.

### LSTM

Uses gates to control:

* What to remember
* What to forget
* What to output

### GRU

A simpler gated architecture than LSTM.

---

<h2 style="
color: #78281F;
border-bottom: 4px solid #E74C3C;
padding-bottom: 8px;
font-weight: 800;
">
🧠 LSTM Intuition
</h2>

LSTM introduces a **cell state** and gates.

Main gates:

```text
Forget Gate
Input Gate
Output Gate
```

Intuition:

```text
Previous memory
      ↓
[ What should I forget? ]
      ↓
[ What should I remember? ]
      ↓
[ What should I output? ]
```

This allows LSTM to preserve useful information for much longer sequences.

---

<h2 style="
color: #1B2631;
border-bottom: 4px solid #5D6D7E;
padding-bottom: 8px;
font-weight: 800;
">
🧠 GRU Intuition
</h2>

GRU simplifies LSTM.

It mainly uses:

* Update Gate
* Reset Gate

GRU generally has fewer parameters than LSTM.

---

<h2 style="
color: #5B2C6F;
border-bottom: 4px solid #AF7AC5;
padding-bottom: 8px;
font-weight: 800;
">
🔄 RNN vs ANN vs CNN
</h2>

| Network | Best suited for                   |
| ------- | --------------------------------- |
| ANN     | Tabular / general structured data |
| CNN     | Images / spatial data             |
| RNN     | Sequential / temporal data        |

### Example

```text
Tabular data
     ↓
    ANN

Image
     ↓
    CNN

Text / Time-series / Speech
     ↓
    RNN
```

---

<h2 style="
color: #0C4130;
border-bottom: 4px solid #45B39D;
padding-bottom: 8px;
font-weight: 800;
">
🌍 Real-World Applications
</h2>

RNNs can be used for:

* 📝 Text generation
* ❤️ Sentiment analysis
* 🌐 Machine translation
* 🎤 Speech recognition
* 📈 Time-series forecasting
* 📊 Sequence classification
* ⌨️ Next-word prediction
* 🎬 Video sequence processing

---

<h2 style="
color: #7E5109;
border-bottom: 4px solid #F5B041;
padding-bottom: 8px;
font-weight: 800;
">
⚙️ RNN Training
</h2>

RNN is trained using:

### Backpropagation Through Time (BPTT)

RNN is essentially **unrolled through time** and backpropagation is performed across those time steps.

```text
x₁ → RNN → h₁ → RNN → h₂ → RNN → h₃
                       ↓
                    Loss

              ← Backpropagation
```

The gradients flow backward through the sequence.

This is why long sequences can cause:

* Vanishing gradients
* Exploding gradients

---

<h2 style="
color: #1B4F72;
border-bottom: 4px solid #3498DB;
padding-bottom: 8px;
font-weight: 800;
">
🧩 Simple PyTorch RNN
</h2>

```python
import torch
import torch.nn as nn

rnn = nn.RNN(
    input_size=10,
    hidden_size=20,
    batch_first=True
)

x = torch.randn(32, 5, 10)

output, hidden = rnn(x)

print(output.shape)
print(hidden.shape)
```

Input:

```text
(32, 5, 10)
```

Meaning:

```text
32 → batch size
5  → sequence length
10 → input features
```

Output:

```text
output → hidden state for every time step
hidden → final hidden state
```

---

<h2 style="
color: #7D3C98;
border-bottom: 4px solid #AF7AC5;
padding-bottom: 8px;
font-weight: 800;
">
⭐ Most Important Intuition
</h2>

Don't think of RNN as:

```text
Input → Neural Network → Output
```

Think of it as:

```text
Current Input
     +
Previous Memory
     ↓
   RNN Cell
     ↓
New Memory
     +
Current Output
```

Repeated for every time step:

```text
x₁ → RNN → h₁
          ↓
x₂ → RNN → h₂
          ↓
x₃ → RNN → h₃
          ↓
x₄ → RNN → h₄
```

---

<h2 style="
color: #0E6251;
border-bottom: 4px solid #48C9B0;
padding-bottom: 8px;
font-weight: 800;
">
🧠 One-Line Definition
</h2>

> **RNN is a neural network designed for sequential data that maintains information from previous time steps using a hidden state.**

---

<h2 style="
color: #943126;
border-bottom: 4px solid #EC7063;
padding-bottom: 8px;
font-weight: 800;
">
🔑 Remember These 7 Things
</h2>

1. **RNN → sequential data**
2. **Hidden state → memory**
3. **Same weights → reused across time**
4. **Sequence → processed step by step**
5. **BPTT → training mechanism**
6. **Vanishing/exploding gradients → major problems**
7. **LSTM & GRU → improved recurrent architectures**

```text
Sequential Data
      ↓
     RNN
      ↓
Hidden State = Memory
      ↓
 BPTT Training
      ↓
Vanishing / Exploding Gradient
      ↓
 LSTM / GRU
```

#lets start 

# <span style="color:#1B4F72;">What is RNN?</span>

> **Recurrent Neural Network (RNN)** is a type of neural network designed for processing **sequential data**.

Unlike traditional **feedforward neural networks**, which process inputs independently, RNNs maintain a **memory of previous inputs** using **loops in their architecture**.

### <span style="color:#2980B9;">Why RNN?</span>

This makes RNNs well-suited for tasks where **context and order matter**, such as:

- **Time Series Forecasting**
- **Speech Recognition**
- **Text Generation**

> **RNN = Sequential Data + Memory of Previous Inputs**

In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv(r"C:\Users\rohit\Downloads\100_Unique_QA_Dataset.csv")

df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of Germany?,Berlin
2,Who wrote 'To Kill a Mockingbird'?,Harper-Lee
3,What is the largest planet in our solar system?,Jupiter
4,What is the boiling point of water in Celsius?,100


In [3]:
#now we have to convert this dataset into numbers 


#tokenize

def tokenize(txt):
    txt = txt.lower()
    txt = txt.replace('?','')
    txt = txt.replace(',','')
    return txt.split()


tokenize("what is the boiliNg point of water?")

['what', 'is', 'the', 'boiling', 'point', 'of', 'water']

In [4]:
#now vocabulary building

vocab  = {'<UNK>' : 0}

def build_vocab(row):
    tokenized_ques = tokenize(row['question'])
    tokenized_ans =  tokenize(row['answer'])
    
    merged_list = tokenized_ques + tokenized_ans

    for token in merged_list:
        if token not in vocab:
            vocab[token] = len(vocab)
    

In [5]:
df.apply(build_vocab,axis = 1)

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [6]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 "'1984'": 67,
 'george-orwell': 68,
 'currency': 69,
 '

In [7]:
#next step is to convert vocab into numerical indices 
def text_to_indices(text, vocab):

  indexed_text = []

  for token in tokenize(text):

    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text
    

In [8]:
text_to_indices("What is chatgpt", vocab)

[1, 2, 0]

In [9]:
import torch
from torch.utils.data import Dataset, DataLoader

In [11]:
class QADataset(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):

    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [12]:
dataset = QADataset(df, vocab)

In [13]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

In [14]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[ 10,  11, 158, 159, 160]]) tensor([161])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[ 10,  75,   3, 298,  19, 299]]) tensor([300])
tensor([[  1,   2,   3, 235,   5, 236]]) tensor([237])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[ 10,  75, 209]]) tensor([210])
tensor([[ 42, 301, 302, 118,  14, 303, 304, 159, 305, 306, 307, 308]]) tensor([309])
tensor([[ 78,  79, 196,  81,  19,   3, 197, 198, 199]]) tensor([200])
tensor([[  1,   2,   3, 181, 182, 183, 184]]) tensor([185])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 42,   2,   3, 276, 212, 277]]) tensor([278])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([262])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[  1,   2,   3,   4,   5, 109]]) 

In [15]:
import torch.nn as nn

In [16]:
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
    self.rnn = nn.RNN(50, 64, batch_first=True)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

learning_rate = 0.001
epochs = 20

model = SimpleRNN(len(vocab))

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# training loop

for epoch in range(epochs):

  total_loss = 0

  for question, answer in dataloader:

    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # loss -> output shape (1,324) - (1)
    loss = criterion(output, answer[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

predict(model, "What is the largest planet in our solar system?")

list(vocab.keys())[7]

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])
Epoch: 1, Loss: 524.372245
Epoch: 2, Loss: 460.847282
Epoch: 3, Loss: 388.899509
Epoch: 4, Loss: 319.819313
Epoch: 5, Loss: 265.679018
Epoch: 6, Loss: 216.258828
Epoch: 7, Loss: 171.561650
Epoch: 8, Loss: 132.824445
Epoch: 9, Loss: 101.685908
Epoch: 10, Loss: 77.465626
Epoch: 11, Loss: 59.488241
Epoch: 12, Loss: 46.969243
Epoch: 13, Loss: 37.259060
Epoch: 14, Loss: 30.494361
Epoch: 15, Loss: 25.354822
Epoch: 16, Loss: 21.171784
Epoch: 17, Loss: 17.787912
Epoch: 18, Loss: 15.086603
Epoch: 19, Loss: 13.024931
Epoch: 20, Loss: 11.363929
jupiter


'paris'