In [10]:
import array 
from array import array 

<h2 style="font-size:32px; color:#1E3A8A; border-bottom:2px solid #DBEAFE; padding-bottom:7px; font-family:Georgia, serif;">
    <strong>Array</strong>
</h2>

<h3 style="font-size:24px; color:#374151;">
    <strong>Definition</strong>
</h3>

<p>
An <strong>array</strong> is a <strong>linear data structure</strong> that stores elements in
<strong>contiguous memory locations</strong>.
</p>

---

<h3 style="font-size:24px; color:#166534;">
    <strong>Properties</strong>
</h3>

<ul style="line-height:1.8;">
<li>Linear Data Structure</li>
<li>Contiguous Memory Allocation</li>
<li>Index-Based Access</li>
<li>Random Access</li>
<li>Same Data Type (Traditional Arrays)</li>
<li>Fixed Size (Traditional Arrays)</li>
<li>Easy Traversal</li>
</ul>

---

<h3 style="font-size:24px; color:#7C2D12;">
    <strong>Why do we use Arrays?</strong>
</h3>

<ul style="line-height:1.8;">
<li>Store multiple values using one variable.</li>
<li>Organize data efficiently.</li>
<li>Fast access using an index.</li>
</ul>

---

<h3 style="font-size:24px; color:#6D28D9;">
    <strong>Time Complexity</strong>
</h3>

<table style="width:100%; border-collapse:separate; border-spacing:8px;">

<tr>
<th align="left">Operation</th>
<th align="left">Time Complexity</th>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Access</div></td>
<td><div style="border-left:4px solid #16A34A; padding:10px;"><strong>O(1)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Update</div></td>
<td><div style="border-left:4px solid #16A34A; padding:10px;"><strong>O(1)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Traversal</div></td>
<td><div style="border-left:4px solid #2563EB; padding:10px;"><strong>O(n)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Linear Search</div></td>
<td><div style="border-left:4px solid #2563EB; padding:10px;"><strong>O(n)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Binary Search (Sorted Array)</div></td>
<td><div style="border-left:4px solid #0891B2; padding:10px;"><strong>O(log n)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Insertion</div></td>
<td><div style="border-left:4px solid #EA580C; padding:10px;"><strong>O(n)</strong></div></td>
</tr>

<tr>
<td><div style="background:#F9FAFB; padding:10px; border-radius:8px;">Deletion</div></td>
<td><div style="border-left:4px solid #DC2626; padding:10px;"><strong>O(n)</strong></div></td>
</tr>

</table>

---

<h3 style="font-size:24px; color:#166534;">
    <strong>Advantages</strong>
</h3>

<ul style="line-height:1.8;">
<li>Fast index access (<strong>O(1)</strong>)</li>
<li>Easy to traverse</li>
<li>Memory efficient</li>
<li>Simple implementation</li>
</ul>

---

<h3 style="font-size:24px; color:#991B1B;">
    <strong>Disadvantages</strong>
</h3>

<ul style="line-height:1.8;">
<li>Fixed size (Traditional Arrays)</li>
<li>Slow insertion (<strong>O(n)</strong>)</li>
<li>Slow deletion (<strong>O(n)</strong>)</li>
<li>Requires contiguous memory</li>
</ul>

---

<h3 style="font-size:24px; color:#0F766E;">
    <strong>Real-Life Examples</strong>
</h3>

<ul style="line-height:1.8;">
<li>Student marks</li>
<li>Daily temperatures</li>
<li>Stock prices</li>
<li>Image pixels</li>
<li>Sensor data</li>
</ul>

---

<h3 style="font-size:24px; color:#7C3AED;">
    <strong>Interview Definition</strong>
</h3>

<blockquote style="border-left:4px solid #A78BFA; padding-left:14px; color:#374151;">
<strong>An array is a linear data structure that stores elements in contiguous memory locations, allowing fast index-based access (<code>O(1)</code>).</strong>
</blockquote>

---

<h3 style="font-size:24px; color:#374151;">
    <strong>Must Remember</strong>
</h3>

<div style="border:1px solid #D1D5DB; border-radius:10px; padding:18px; width:340px; background:#FCFCFC; font-family:'Consolas', monospace; line-height:1.8;">

<strong>Array</strong><br>
│<br>
├── Linear Data Structure<br>
├── Contiguous Memory<br>
├── Index-Based Access<br>
├── Access → O(1)<br>
├── Traversal → O(n)<br>
├── Search → O(n)<br>
├── Binary Search → O(log n)<br>
├── Insertion → O(n)<br>
└── Deletion → O(n)

</div>

<h2 style="font-size:30px; color:#1E3A8A; border-bottom:2px solid #DBEAFE; padding-bottom:7px; font-family:Georgia, serif;">
    <strong>Methods to Create an Array in Python</strong>
</h2>

<p>
We can create a Python array using the following methods:
</p>

<ol style="line-height:1.9;">
<li><strong>Using the <code>array</code> Module</strong></li>
<li><strong>Using the <code>NumPy</code> Module (most useful)</strong></li>
</ol>

## <mark>Creating a array using array module 

| Type Code | Data Type          | Byte Size | Description                |
| :-------: | ------------------ | :-------: | -------------------------- |
| `'b'`     | Signed Byte        | 1 Byte    | Signed integer             |
| `'B'`     | Unsigned Byte      | 1 Byte    | Unsigned integer           |
| `'h'`     | Signed Short       | 2 Bytes   | Signed short integer       |
| `'H'`     | Unsigned Short     | 2 Bytes   | Unsigned short integer     |
| `'i'`     | Signed Integer     | 2 or 4*   | Signed integer             |
| `'I'`     | Unsigned Integer   | 2 or 4*   | Unsigned integer           |
| `'l'`     | Signed Long        | 4 Bytes   | Signed long integer        |
| `'L'`     | Unsigned Long      | 4 Bytes   | Unsigned long integer      |
| `'q'`     | Signed Long Long   | 8 Bytes   | Signed long long integer   |
| `'Q'`     | Unsigned Long Long | 8 Bytes   | Unsigned long long integer |
| `'f'`     | Float              | 4 Bytes   | Single-precision float     |
| `'d'`     | Double             | 8 Bytes   | Double-precision float     |
| `'u'`     | Unicode Character* | 2 Bytes   | Unicode character          |

In [ ]:
# #syntax to create a array 

# from array import array

# arr = array(typecode, [elements])

In [9]:
from array import array

arr = array('i', [10, 20, 30, 90, 50])

print(arr)

array('i', [10, 20, 30, 90, 50])


<h2 style="font-size:30px; color:#1E3A8A; border-bottom:2px solid #DBEAFE; padding-bottom:7px; font-family:Georgia, serif;">
    <strong>Array Module Limitation</strong>
</h2>

<p>

The <strong><code>array</code> module</strong> is designed to store only
<strong>fixed-size primitive data types</strong> (mainly numeric values).
It <strong>cannot store Python strings or mixed data types.</strong>

</p>

<div style="border-left:4px solid #2563EB; padding:10px 14px; margin-top:12px;">

<strong>For strings, use Python Lists.</strong>

</div>

In [14]:
#we can also build one only for unicode character(single character)

chr = array('u',["H","P"])

chr

C:\Users\shobh\AppData\Local\Temp\ipykernel_8924\2246712414.py:3: DeprecationWarning: The 'u' type code is deprecated and will be removed in Python 3.16
  chr = array('u',["H","P"])


array('u', 'HP')

<h2 style="font-size:30px; color:#1E3A8A; border-bottom:2px solid #DBEAFE; padding-bottom:7px; font-family:Georgia, serif;">
    <strong>Array Operations </strong>
</h2>


In [ ]:
#know typecode of an arr

print(arr.typecode)


#know length of array

print(f"Length : {len(arr)}")


#access Elements

print(f"First Element  : {arr[0]}")
print(f"Last Element   : {arr[-1]}")


#update Elements

print(f"Before : {arr}")

arr[3] = 980

print(f"After  : {arr}")

In [ ]:
#append Element

print(f"Before : {arr}")

arr.append(100)

print(f"After  : {arr}")


#insert Element

print(f"Before : {arr}")

arr.insert(2, 999)

print(f"After  : {arr}")


#remove Element

print(f"Before : {arr}")

arr.remove(20)

print(f"After  : {arr}")


#pop Element

print(f"Before : {arr}")

removed = arr.pop()

print(f"Removed : {removed}")
print(f"After   : {arr}")


#find Index

print(f"Index of 980 : {arr.index(980)}")

In [21]:
#count Occurrences

arr.append(10)
arr.append(10)

print(f"Count of 10 : {arr.count(10)}")


#reverse Array

print(f"Before : {arr}")

arr.reverse()

print(f"After  : {arr}")


#traverse Array

print("Traversal :", end=" ")

for i in arr:
    print(i, end=" ")

print()


#convert Array to List

lst = arr.tolist()

print(lst)
print(type(lst))

Count of 10 : 5
Before : array('i', [10, 10, 50, 980, 30, 999, 10, 10, 10])
After  : array('i', [10, 10, 10, 999, 30, 980, 50, 10, 10])
Traversal : 10 10 10 999 30 980 50 10 10 
[10, 10, 10, 999, 30, 980, 50, 10, 10]
<class 'list'>


In [20]:
arr2 = array('i',[40,32,44,55,24])
print("\n Before:",arr2,"\n")
print("Traversal :", end=" ")

for i in arr2:
    print(i, end=" ")

print()



 Before: array('i', [40, 32, 44, 55, 24]) 

Traversal : 40 32 44 55 24 


In [25]:
arr3 = array('i',[40,32,44,55,24])

print(f"Before : {arr3}")

arr3.pop()

print(f"After  : {arr3}")

Before : array('i', [40, 32, 44, 55, 24])
After  : array('i', [40, 32, 44, 55])


In [29]:
#copy existing values in a new array 

copyArr = array(arr3.typecode, (i+1 for i in arr3))      #use list comprehension

copyArr

array('i', [41, 33, 45, 56])

In [33]:
# Reverse a arr 

rev = arr3[::-1]
print(arr3)
rev

array('i', [40, 32, 44, 55])


array('i', [55, 44, 32, 40])

<h3 style="font-size:24px; color:#991B1B;">
    <strong>Array Slicing and Indexing</strong>
</h3>


<b>array</b>[start : stop : step]

In [35]:
arr = array('i', [10, 20, 30, 40, 50, 60])

print("Original Array :", arr)

print("\nIndexing")

print("First Element       :", arr[0])

print("Third Element       :", arr[2])

print("Last Element        :", arr[-1])

print("Second Last Element :", arr[-2])


#Slicing

print("arr[:]    :", arr[:])
print("arr[1:4]  :", arr[1:4])
print("arr[:3]   :", arr[:3])

print("arr[3:]   :", arr[3:])

print("arr[::2]  :", arr[::2])
print("arr[::-1] :", arr[::-1])
arr[1::2]

Original Array : array('i', [10, 20, 30, 40, 50, 60])

Indexing
First Element       : 10
Third Element       : 30
Last Element        : 60
Second Last Element : 50
arr[:]    : array('i', [10, 20, 30, 40, 50, 60])
arr[1:4]  : array('i', [20, 30, 40])
arr[:3]   : array('i', [10, 20, 30])
arr[3:]   : array('i', [40, 50, 60])
arr[::2]  : array('i', [10, 30, 50])
arr[::-1] : array('i', [60, 50, 40, 30, 20, 10])


array('i', [20, 40, 60])

In [40]:
#take input from user to allocate it in array 


arr = array('i', [])

n = int(input("Enter a number"))

for i in range(n):
    arr.append(int(input("Enter next input")))

print(*arr)

Enter a number 1
Enter next input 2


2


In [42]:
#know index of any element 

arr = array('i', [10, 20, 30, 40, 50, 60])


arr.index(60)



5

## <mark>Creating a array using numpy module 

<h2 style="font-size:30px; color:#1E3A8A; border-bottom:2px solid #DBEAFE; padding-bottom:6px;">
    <strong>Why is NumPy Better than the <code>array</code> Module?</strong>
</h2>

<ul style="line-height:1.8;">

<li>Supports <strong>1D, 2D, 3D, and higher-dimensional arrays.</strong></li>

<li>Faster and more <strong>memory-efficient</strong> for numerical computations.</li>

<li>Provides powerful <strong>vectorized mathematical operations.</strong></li>

<li>Offers built-in functions for <strong>statistics, linear algebra, and matrix operations.</strong></li>

<li>Integrates with <strong>Pandas, Matplotlib, Scikit-learn, TensorFlow, and PyTorch.</strong></li>

<li>Industry standard for <strong>AI, Machine Learning, Deep Learning, and Data Science.</strong></li>

<li>Better suited for handling <strong>large datasets.</strong></li>

</ul>

In [55]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])


for x in arr:
    print(x,end = ' ')
    
print('\n')

for i in range(len(arr)):
    print(arr[i],end = ' ')
    

10 20 30 40 50 

10 20 30 40 50 

In [57]:
#we can also create hetrogenrous array using numpy module 


arr_hetro = np.array([10, 20, 30, 40, 50,9.0,9.383739,"Harsh"])

print(arr_hetro)

['10' '20' '30' '40' '50' '9.0' '9.383739' 'Harsh']


In [58]:
#how to simply convert datatypes iun numpy array 

arr = np.array([10, 20, 30, 40, 50])


new_arr = np.array([10, 20, 30, 40, 50],float)

new_arr

array([10., 20., 30., 40., 50.])

In [62]:
#create a array with arthemetic progresion using numpy 

#syntax = linspace(start :end: no.of partition)
arr = linspace(10,20,4)

for i in arr:
    print(i)

10.0
13.333333333333334
16.666666666666668
20.0


In [65]:
#create an array containing a sequence of numbers.

#syntax ; np.arange(start, stop, step)

arr = np.arange(2, 11, 2)

print(arr)

[ 2  4  6  8 10]


In [66]:
#create an array containing logarithmically spaced numbers (powers of a base).

#syntax : np.logspace(start, stop, num=50, base=10)

arr = np.logspace(0, 3, 4)

print(arr)

[   1.   10.  100. 1000.]



Explanation:

start = 0 → 10⁰ = 1

stop = 3 → 10³ = 1000

num = 4 → Generate 4 values

base = 10 → Use powers of 10

In [71]:
#zeros array 
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
#of 1 constant number 


# syntax  ; np.full(size,number)


arr = np.full(10,4)

arr

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])